package com.aonon.pixelslot;

import android.content.Context;
import android.graphics.*;
import android.util.Base64;
import android.view.MotionEvent;
import java.io.*;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;

/** v0.8 clean renderer: V5 is state engine only; old drawing is never called. */
public class PixelSlotV8View extends PixelSlotV5View {
  private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), bp=new Paint(Paint.ANTI_ALIAS_FLAG);
  private final RectF spin=new RectF(); private final Bitmap[] girl=new Bitmap[3];
  private Method update,start; private boolean ok;
  private Field shown,pulse,coins,spins,wins,stage,spinning,reach,premium,revival,celeEnd,premStart,premEnd,revStart,revFlash,cutStart,cutEnd,rewardStart,rewardEnd,cutTitle,cutMsg,cutType,lastReward;
  private static final String[] N={"モモ","ルナ","ミオ"};
  private static final int[] A={Color.rgb(255,126,170),Color.rgb(166,139,241),Color.rgb(92,218,220)};
  private static final float[][] B={{.60156f,.34286f,.89062f,.54286f},{.58886f,.38079f,.92573f,.59768f},{.27106f,.43852f,.83516f,.65369f}};

  public PixelSlotV8View(Context c){super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);girl[0]=asset("v08c_momo_",1);girl[1]=asset("v08c_luna_",1);girl[2]=asset("v08c_mio_",1);reflect();}
  private Bitmap asset(String pre,int n){try{StringBuilder s=new StringBuilder();for(int i=0;i<n;i++)try(BufferedReader r=new BufferedReader(new InputStreamReader(getContext().getAssets().open(pre+i+".txt"),StandardCharsets.US_ASCII))){String x;while((x=r.readLine())!=null)s.append(x.trim());}byte[] d=Base64.decode(s.toString(),Base64.DEFAULT);return BitmapFactory.decodeByteArray(d,0,d.length);}catch(Exception e){e.printStackTrace();return null;}}
  private static Field f(Class<?> c,String n)throws Exception{Field x=c.getDeclaredField(n);x.setAccessible(true);return x;}
  private static Method m(Class<?> c,String n,Class<?>...a)throws Exception{Method x=c.getDeclaredMethod(n,a);x.setAccessible(true);return x;}
  private void reflect(){try{Class<?> c=PixelSlotV5View.class;update=m(c,"update",long.class);start=m(c,"startSpin");shown=f(c,"shown");pulse=f(c,"pulseUntil");coins=f(c,"coins");spins=f(c,"spins");wins=f(c,"wins");stage=f(c,"reachStage");spinning=f(c,"spinning");reach=f(c,"reach");premium=f(c,"premium");revival=f(c,"revivalActive");celeEnd=f(c,"celebrationUntil");premStart=f(c,"premiumStart");premEnd=f(c,"premiumUntil");revStart=f(c,"revivalStart");revFlash=f(c,"revivalFlashUntil");cutStart=f(c,"cutStart");cutEnd=f(c,"cutUntil");rewardStart=f(c,"rewardStart");rewardEnd=f(c,"rewardUntil");cutTitle=f(c,"cutTitle");cutMsg=f(c,"cutMessage");cutType=f(c,"cutType");lastReward=f(c,"lastReward");ok=true;}catch(Exception e){e.printStackTrace();}}
  private int I(Field x)throws Exception{return x.getInt(this);} private long L(Field x)throws Exception{return x.getLong(this);} private boolean Z(Field x)throws Exception{return x.getBoolean(this);} private String S(Field x)throws Exception{return (String)x.get(this);}

  @Override protected void onDraw(Canvas c){
    int w=getWidth(),h=getHeight();long now=System.currentTimeMillis();
    if(!ok){c.drawColor(Color.rgb(18,11,30));text(c,"v0.8 renderer error",w/2f,h/2f,w*.05f,Color.WHITE,Paint.Align.CENTER);return;}
    try{update.invoke(this,now);bg(c,w,h,now);header(c,w,h);machine(c,w,h,now);button(c,w,h);if(Z(reach)&&Z(spinning)&&I(stage)>=3)hype(c,w,h,now,I(stage));if(now<L(celeEnd))celebrate(c,w,h,now,Z(premium));if(now<L(cutEnd))cutin(c,w,h,now);if(now<L(premEnd))premium(c,w,h,now);if(Z(revival))revival(c,w,h,now);if(now<L(revFlash)){p.setColor(Color.argb((int)(180*Math.max(0,1-(L(revFlash)-now)/900f)),255,230,255));c.drawRect(0,0,w,h,p);}if(now<L(rewardEnd))reward(c,w,h,now);long[] pu=(long[])pulse.get(this);if(Z(spinning)||Z(revival)||now<L(celeEnd)||now<L(cutEnd)||now<L(premEnd)||now<L(rewardEnd)||now<pu[0]||now<pu[1]||now<pu[2])postInvalidateOnAnimation();}catch(Throwable e){e.printStackTrace();}
  }
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_UP&&spin.contains(e.getX(),e.getY())){try{start.invoke(this);invalidate();}catch(Exception x){x.printStackTrace();}return true;}return true;}
  @Override public boolean performClick(){super.performClick();return true;}

  private void bg(Canvas c,int w,int h,long n)throws Exception{int t=Color.rgb(30,20,46),b=Color.rgb(13,9,23);if(Z(spinning)&&I(stage)>=4)t=Color.rgb(70,14,78);if(n<L(celeEnd)){t=Z(premium)?Color.rgb(88,55,5):Color.rgb(82,17,54);b=Z(premium)?Color.rgb(28,15,2):Color.rgb(48,13,20);}p.setShader(new LinearGradient(0,0,0,h,t,b,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.argb(16,255,207,236));c.drawCircle(w*.1f,h*.15f,w*.29f,p);}
  private void header(Canvas c,int w,int h)throws Exception{text(c,"PIXEL SLOT",w/2f,h*.072f,w*.071f,Color.rgb(255,221,244),Paint.Align.CENTER);text(c,"静かな通常時。来た時だけ全部盛り。",w/2f,h*.107f,w*.026f,Color.rgb(190,176,204),Paint.Align.CENTER);text(c,"SPIN  "+I(spins),w*.055f,h*.15f,w*.029f,Color.rgb(235,226,244),Paint.Align.LEFT);coin(c,w*.408f,h*.135f,w*.021f);text(c,"COIN  "+I(coins),w*.54f,h*.15f,w*.031f,Color.rgb(255,226,105),Paint.Align.CENTER);text(c,"WIN  "+I(wins),w*.945f,h*.15f,w*.029f,Color.rgb(235,226,244),Paint.Align.RIGHT);}
  private void machine(Canvas c,int w,int h,long n)throws Exception{RectF box=new RectF(w*.045f,h*.18f,w*.955f,h*.735f);p.setColor(Color.argb(225,55,37,76));c.drawRoundRect(box,w*.05f,w*.05f,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w*(Z(spinning)&&I(stage)>=3?.010f:.006f));p.setColor(Z(spinning)&&I(stage)>=3?Color.rgb(255,150,150):Color.rgb(184,124,174));c.drawRoundRect(box,w*.05f,w*.05f,p);p.setStyle(Paint.Style.FILL);float[] x={w*.20f,w*.50f,w*.80f};int[] nums=(int[])shown.get(this);boolean win=n<L(celeEnd);for(int i=0;i<3;i++){float bob=(float)Math.sin(n/360.0+i)*h*.0015f,jump=win?-(float)Math.abs(Math.sin((n%390)/390f*Math.PI))*h*(.024f+i*.003f):0,trem=Z(reach)&&Z(spinning)&&i==2&&I(stage)>=3?(float)Math.sin(n/13.0)*w*.012f:0;RectF d=sprite(c,girl[i],x[i]+trem,h*.59f+bob+jump,w*.255f,h*.31f);digit(c,d,i,nums[i]);text(c,N[i],x[i],h*.69f,w*.03f,Color.rgb(213,199,222),Paint.Align.CENTER);}if(Z(reach)&&Z(spinning)){String[] q={"","……？","もしかして…","リーチ！！","まだ続く…！","激アツッ！！","限界突破…！","止まれぇぇぇ！！"};int st=Math.min(7,I(stage));text(c,q[st],w/2f,h*.72f,w*(.033f+Math.max(0,st-1)*.006f),st<=2?Color.rgb(220,211,228):Color.rgb(255,236,102),Paint.Align.CENTER);}}
  private RectF sprite(Canvas c,Bitmap b,float cx,float base,float mw,float mh){if(b==null)return new RectF(cx-mw/2,base-mh,cx+mw/2,base);float s=Math.min(mw/b.getWidth(),mh/b.getHeight()),dw=b.getWidth()*s,dh=b.getHeight()*s;RectF d=new RectF(cx-dw/2,base-dh,cx+dw/2,base);c.drawBitmap(b,null,d,bp);return d;}
  private void digit(Canvas c,RectF d,int ch,int n){float[] z=B[ch];RectF r=new RectF(d.left+d.width()*z[0],d.top+d.height()*z[1],d.left+d.width()*z[2],d.top+d.height()*z[3]);float sz=Math.min(r.height()*.67f,r.width()*.58f);p.setTypeface(Typeface.create(Typeface.MONOSPACE,Typeface.BOLD));p.setTextSize(sz);p.setTextAlign(Paint.Align.CENTER);Paint.FontMetrics fm=p.getFontMetrics();float y=r.centerY()-(fm.ascent+fm.descent)/2;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(2,sz*.045f));p.setColor(Color.WHITE);c.drawText(""+n,r.centerX(),y,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(69,43,103));c.drawText(""+n,r.centerX(),y,p);}
  private void button(Canvas c,int w,int h)throws Exception{float bw=w*.64f,bh=h*.105f,cx=w/2f,cy=h*.85f;spin.set(cx-bw/2,cy-bh/2,cx+bw/2,cy+bh/2);p.setColor(Z(spinning)||Z(revival)?Color.rgb(92,78,108):Color.rgb(219,83,148));p.setShadowLayer(w*.018f,0,h*.006f,Color.argb(100,0,0,0));c.drawRoundRect(spin,bh/2,bh/2,p);p.clearShadowLayer();String s=!Z(spinning)&&!Z(revival)?"SPIN!":I(stage)<=1?"……":I(stage)==2?"ん……？":I(stage)<=4?"来てる…！":"うわあああ！！";text(c,s,cx,cy+h*.018f,w*.059f,Color.WHITE,Paint.Align.CENTER);text(c,"1 PLAY  10 COIN",cx,h*.93f,w*.027f,Color.rgb(177,163,190),Paint.Align.CENTER);}
  private void hype(Canvas c,int w,int h,long n,int st){int rays=12+st*6;p.setStrokeWidth(w*.004f);for(int i=0;i<rays;i++){double a=(Math.PI*2*i/rays)+n/900.0;float r1=w*.23f,r2=w*(.32f+st*.035f);p.setColor(Color.argb(35+st*9,255,210,80));c.drawLine(w/2f+(float)Math.cos(a)*r1,h*.49f+(float)Math.sin(a)*r1,w/2f+(float)Math.cos(a)*r2,h*.49f+(float)Math.sin(a)*r2,p);}}
  private void celebrate(Canvas c,int w,int h,long n,boolean pr){for(int i=0;i<55;i++){float x=((i*173+(n/12))%1200)/1200f*w,y=((i*97+(n/8))%1500)/1500f*h;p.setColor(Color.argb(150,pr?255:(120+i*2)%255,pr?215:100+(i*3)%155,pr?60:200));c.drawCircle(x,y,w*(.003f+(i%4)*.0015f),p);}}
  private void cutin(Canvas c,int w,int h,long n)throws Exception{long a=L(cutStart),e=L(cutEnd);float t=Math.min(1f,(n-a)/(float)Math.max(1,e-a)),vis=Math.min(Math.min(1,t/.13f),t>.86f?Math.max(0,(1-t)/.14f):1);int type=I(cutType),ch=(type==2||type==11)?0:(type==3?1:2),ac=cutColor(type);boolean big=type==2||type==6||type==9||type==10||type==11;float top=big?h*.15f:h*.22f,bot=big?h*.50f:h*.42f,slide=(1-vis)*(type%2==0?-w:w);c.save();c.translate(slide,0);p.setColor(Color.rgb(18,10,33));c.drawRect(0,top,w,bot,p);p.setColor(ac);c.drawRect(0,top,w,top+h*.009f,p);c.drawRect(0,bot-h*.009f,w,bot,p);RectF ar=new RectF(w*.02f,top+h*.01f,w*.30f,bot-h*.01f);portrait(c,girl[ch],ar);text(c,S(cutTitle),w*.335f,top+h*(big?.10f:.075f),w*(big?.073f:.06f),ac,Paint.Align.LEFT);oneLine(c,S(cutMsg),w*.335f,top+h*(big?.16f:.13f),w*.034f,Color.WHITE,w*.62f);c.restore();}
  private int cutColor(int t){if(t==2||t==11)return Color.rgb(255,222,64);if(t==5)return Color.rgb(255,122,44);if(t==6||t==9)return Color.rgb(255,55,100);return Color.rgb(255,105,181);}
  private void portrait(Canvas c,Bitmap b,RectF a){if(b==null)return;RectF src=new RectF(b.getWidth()*.08f,0,b.getWidth()*.92f,b.getHeight()*.68f);float s=Math.max(a.width()/src.width(),a.height()/src.height()),dw=src.width()*s,dh=src.height()*s;RectF d=new RectF(a.centerX()-dw/2,a.centerY()-dh/2,a.centerX()+dw/2,a.centerY()+dh/2);c.save();c.clipRect(a);c.drawBitmap(b,new Rect((int)src.left,(int)src.top,(int)src.right,(int)src.bottom),d,bp);c.restore();}
  private void premium(Canvas c,int w,int h,long n)throws Exception{long e=n-L(premStart);p.setColor(Color.argb(e<900?230:190,5,3,0));c.drawRect(0,0,w,h,p);if(e<900){text(c,"……",w/2f,h*.48f,w*.075f,Color.rgb(255,229,120),Paint.Align.CENTER);return;}text(c,"PREMIUM",w/2f,h*.30f,w*.10f,Color.rgb(255,224,80),Paint.Align.CENTER);text(c,"777",w/2f,h*.43f,w*.16f,Color.WHITE,Paint.Align.CENTER);if(e>3500){for(int i=0;i<3;i++)sprite(c,girl[i],w*(.20f+i*.30f),h*.78f,w*.22f,h*.26f);}}
  private void revival(Canvas c,int w,int h,long n)throws Exception{long e=n-L(revStart);p.setColor(Color.argb(235,0,0,0));c.drawRect(0,0,w,h,p);text(c,e<800?"……":"……まだ。",w/2f,h*.49f,w*.065f,Color.rgb(225,210,235),Paint.Align.CENTER);}
  private void reward(Canvas c,int w,int h,long n)throws Exception{long e=n-L(rewardStart),dur=Math.max(1,L(rewardEnd)-L(rewardStart));float k=(float)Math.sin(Math.min(1,e/(float)dur)*Math.PI);float cy=h*.22f;coin(c,w*.39f,cy,w*.03f*(1+k*.3f));text(c,"+"+I(lastReward),w*.44f,cy+w*.012f,w*.06f,Color.rgb(255,228,80),Paint.Align.LEFT);}
  private void coin(Canvas c,float x,float y,float r){p.setColor(Color.rgb(255,190,35));c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(r*.18f);p.setColor(Color.rgb(255,235,125));c.drawCircle(x,y,r*.72f,p);p.setStyle(Paint.Style.FILL);}
  private void text(Canvas c,String s,float x,float y,float size,int color,Paint.Align al){p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));p.setTextAlign(al);p.setTextSize(size);p.setColor(color);c.drawText(s,x,y,p);}
  private void oneLine(Canvas c,String s,float x,float y,float size,int color,float max){p.setTextSize(size);p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));while(p.measureText(s)>max&&p.getTextSize()>15)p.setTextSize(p.getTextSize()*.94f);p.setTextAlign(Paint.Align.LEFT);p.setColor(color);c.drawText(s,x,y,p);}
}
